In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

step size

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

linspace

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

identity matix

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

random

In [24]:
np.random.rand()

0.5627697113320822

In [25]:
np.random.rand(5,5)

array([[0.81241254, 0.51450848, 0.5137674 , 0.64660096, 0.42528361],
       [0.84026921, 0.65745825, 0.03951439, 0.67287337, 0.4095974 ],
       [0.83623719, 0.34797429, 0.8897909 , 0.42982387, 0.83121716],
       [0.09179874, 0.29450147, 0.4179483 , 0.16311738, 0.93925054],
       [0.35987207, 0.85551297, 0.59735903, 0.23423772, 0.10338908]])

random normal distribution

In [26]:
np.random.randn(2)

array([ 0.62479428, -0.26156313])

In [27]:
np.random.randn(4,4)

array([[-0.4183655 ,  1.08716586, -0.6045289 , -0.10256475],
       [-0.27014771, -0.45607072, -0.43326345,  0.97329763],
       [ 0.38215185, -1.40907901, -0.06249617, -0.53540515],
       [-0.39005639, -0.0867487 , -0.01395337,  1.91633141]])

rand int

In [28]:
np.random.randint(1,100)

52

In [31]:
np.random.randint(1,100,10)

array([44, 43, 80,  1, 26, 21, 24, 26, 98, 62])

array

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)

In [35]:
ranarr

array([32, 32, 45, 47, 49, 27, 23,  7, 20, 32])

reshape method

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

max or min or index methods

In [37]:
ranarr

array([32, 32, 45, 47, 49, 27, 23,  7, 20, 32])

In [38]:
ranarr.max()

49

In [39]:
ranarr.min()

7

In [40]:
ranarr

array([32, 32, 45, 47, 49, 27, 23,  7, 20, 32])

Index of max or min

In [41]:
ranarr.argmax()

4

In [42]:
ranarr.argmin()

7

shape of vector

In [43]:
arr.shape

(25,)

In [44]:
arr = arr.reshape(5,5)

In [45]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.shape

(5, 5)

data type in array

In [47]:
arr.dtype

dtype('int64')

In [48]:
from numpy.random import randint

In [49]:
randint(2,10)

4